#!/usr/bin/env python3
# _*_ coding: utf-8 _*_

"""
A psutil-based command to display customizable system usage info in a single line, intended for Tint2 executors

Author: Piotr Miller
e-mail: nwg.piotr@gmail.com
Website: http://nwg.pl
Project: https://github.com/nwg-piotr/psuinfo
License: GPL3

Inspired by https://github.com/tknomanzr/scripts/blob/master/tint2/executors/cpu.py by William Bradley (@tknomanzr)
"""

import sys
import time
import os
from functools import lru_cache
import psutil


def main():
    time_start = time.time()
    fahrenheit = False
    names = False
    testing = False
    components = "gStfM"
    separator = "  "
    home = os.getenv("HOME")
    path_to_icon = None
    which = None
    c_name = None

    for arg in sys.argv[1:]:
        if arg in ("-h", "--help"):
            print_help()
            exit(0)

        elif arg == "-F":
            fahrenheit = True

        elif arg == "-N":
            names = True

        elif arg == "-T":
            testing = True

        elif arg.startswith("-C"):
            components = arg[2:]

        elif arg.startswith("-S"):
            if arg[2:].isdigit():
                separator = " " * int(arg[2:])
            else:
                separator = arg[2:]

        elif arg.startswith("-W"):
            if arg[2:].isdigit():
                which = int(arg[2:])

        elif arg.startswith("-I"):
            # We can only have one icon per executor
            components = arg[2]
            if components == "k":
                path_to_icon = net_icon(home, *upload_download())
            else:
                path_to_icon = icon_path(home, components)

        elif arg.startswith("-M"):
            # We can only have a custom name for a single component
            components = components[0]
            names = True
            c_name = arg[2:]

        elif arg.upper() == "-ALL":
            components = "gpaQStfMcWDUk"
            names = True
            testing = True

    def nameAs(default):
        return c_name or default if names else ""

    # Build output after components
    output = []

    for char in components:
        if char == "g":
            if pcpu():
                output.append((c_name or "") + graph_per_cpu(pcpu()))

        elif char == "p":
            if pcpu():
                output.append(nameAs("CPU: ") + per_cpu(pcpu()))

        elif char == "a":
            if avg():
                output.append(nameAs("avCPU: ") + str(avg()).ljust(4) + "%")

        elif char == "q":
            if freqs():
                output.append(
                    nameAs("CPU: ") +
                    freq_per_cpu(freqs())[0][:-1] + " GHz"
                )

        elif char == "Q":
            if freqs():
                _result = freq_per_cpu(freqs())
                output.append(
                    nameAs("CPU: ") +
                    _result[0][:-1] + "/" +
                    str(_result[1]) + " GHz"
                )

        elif char == "s":
            if speed():
                output.append(
                    nameAs("SPD: ") +
                    str(round(speed()[0] / 1000, 1)) + " GHz"
                )

        elif char == "S":
            if speed():
                output.append(
                    nameAs("avSPD: ") +
                    str(round(speed()[0] / 1000, 1)) + "/" +
                    str(round(speed()[2] / 1000, 1)) + " GHz"
                )

        elif char == "t":
            temp = psutil.sensors_temperatures(fahrenheit)

            if not temp:
                continue

            if "k10temp" in temp.keys():
                # ryzen, multiple Die temperatures for threadripper/Epyc
                try:
                    ryzen_die_temps = tuple(
                        sensor.current
                        for sensor in temp["k10temp"]
                        if sensor.label == 'Tdie' or sensor.label == 'Tctl'
                    )
                    if ryzen_die_temps:
                        temper = str(int(max(ryzen_die_temps)))
                except Exception:
                    pass
            elif "zenpower" in temp.keys():
                # zen3 is not supported in k10. Fix is to load zenpower and unload k10
                try:
                    ryzen_die_temps = tuple(
                        sensor.current
                        for sensor in temp["zenpower"]
                        if sensor.label == 'Tdie' or sensor.label == 'Tctl'
                    )
                    if ryzen_die_temps:
                        temper = str(int(max(ryzen_die_temps)))
                except Exception:
                    pass
            elif "coretemp" in temp.keys():
                # intel
                temper = str(int(temp["coretemp"][0][1]))
            else:
                temper = ""

            if temper:
                name = nameAs("CORE: ")
                output.append(name + temper + ("℉" if fahrenheit else "℃"))

        elif char == "f":
            if fans():
                fan0 = next(iter(fans().values()))
                output.append(nameAs("FAN: ") + str(fan0[0][1]) + "/m")

        elif char == 'm':
            if memory():
                output.append(
                    nameAs("MEM: ") +
                    str(round((memory()[0] - memory()[1]) / 1073741824, 1)) + " GB"
                )

        elif char == 'M':
            if memory():
                output.append(
                    nameAs("MEM: ") +
                    str(round((memory()[3]) / 1073741824, 1)) + "/" +
                    str(round(memory()[0] / 1073741824, 1)) + " GB"
                )

        elif char == 'c':
            if memory():
                output.append(nameAs("MEM: ") + str(memory()[2]) + "%")

        elif char == 'C':
            if memory():
                output.append(nameAs("MEM: ") + str(100 - memory()[2]) + "%")

        elif char == 'u':
            if b_time():
                up_time = int(time.time()) - b_time()
                m, s = divmod(up_time, 60)
                h, m = divmod(m, 60)
                output.append(nameAs("UP: ") + "%d:%02d" % (h, m))

        elif char == 'U':
            if b_time():
                up_time = int(time.time()) - b_time()
                m, s = divmod(up_time, 60)
                h, m = divmod(m, 60)
                output.append(nameAs("UP: ") + "%d:%02d:%02d" % (h, m, s))

        elif char == "w":
            if swap():
                output.append(
                    nameAs("SWAP: ") +
                    str(round(swap()[1] / 1073741824, 1)) + " GB"
                )

        elif char == "W":
            if swap():
                output.append(
                    nameAs("SWAP: ") +
                    str(round(swap()[1] / 1073741824, 1)) + "/" +
                    str(round(swap()[0] / 1073741824, 1)) + " GB"
                )

        elif char == "x":
            if swap():
                output.append(nameAs("SWAP: ") + str(swap()[3]) + "%")

        elif char == "d" or char == "n":
            i = 0 if char == "d" else 1
            for *_names, usage in disk_usage_data(which):
                output.append(_names[i] + ": " + str(usage.percent) + "%")

        elif char == "D" or char == "N":
            i = 0 if char == "d" else 1
            for *_names, usage in disk_usage_data(which):
                output.append(
                    _names[i] + ": " +
                    str(round(usage.used / 1073741824, 1)) + "/" +
                    str(round(usage.total / 1073741824, 1)) + " GB"
                )

        elif char == "k":
            upload, download = upload_download()
            output.append(
                nameAs("Net: ") +
                '{:0.2f}  '.format(upload) +
                '{:0.2f} kB/s'.format(download)
            )

    if testing:
        output.append("[" + str(round(time.time()) - round(time_start)) + "s]")

    if path_to_icon:
        print(path_to_icon)
    print(separator.join(output))


@lru_cache
def pcpu():
    return psutil.cpu_percent(interval=1, percpu=True)

@lru_cache
def avg():
    return psutil.cpu_percent(interval=1)

@lru_cache
def speed():
    return psutil.cpu_freq(False)

@lru_cache
def freqs():
    return psutil.cpu_freq(True)

@lru_cache
def fans():
    return psutil.sensors_fans()

@lru_cache
def memory():
    return psutil.virtual_memory()

@lru_cache
def swap():
    return psutil.swap_memory()

@lru_cache
def b_time():
    return psutil.boot_time()

@lru_cache
def disk_usage_data(which: int):
    tpl = tuple(
        (
         partition.device.split("/")[-1].upper(),
         partition.mountpoint,
         psutil.disk_usage(partition.mountpoint)
        ) for partition in psutil.disk_partitions()
    )
    return tpl[which:which+1] if which is not None else tpl

def upload_download():
    xfer_start = psutil.net_io_counters()
    time.sleep(1)
    xfer_end = psutil.net_io_counters()
    upload = (xfer_end[0] - xfer_start[0]) / 1024
    download = (xfer_end[1] - xfer_start[1]) / 1024
    return upload, download

def per_cpu(result):
    string = ""
    for val in result:
        proc = str(int(round(val, 1)))
        if len(proc) < 2:
            proc = " " + proc
        string += proc + "% "
    return string


def freq_per_cpu(result):
    string = ""
    max_freq = 0
    for val in result:
        freq = str(round(val[0] / 1000, 1))
        string += freq + "|"
        max_freq = str(round(val[2] / 1000, 1))

    return string, max_freq


def graph_per_cpu(result):
    graph = "_▁▂▃▄▅▆▇███"

    string = ""
    for val in result:
        proc = int(round(val / 10, 0))
        string += graph[proc]
    return string


def print_help():

    print("\npsuinfo [-C{components}] | [-I{component}] [-F] [-N] [-S<number>] | [-S<string>] [-T] [-W{number}] [-all] [-h] [--help]")

    print("\n-C defines multiple components. -I defines a single component. If none given, -CgStfM argument will be used by default.\n")
    print("  g - (g)raphical CPU load bar")
    print("  p - (p)ercentage for each core (text)")
    print("  a - (a)verage CPU load (text)")
    print("  q - fre(q)ency for each thread")
    print("  Q - fre(Q)ency for each thread/max frequency")
    print("  s - current CPU (s)peed")
    print("  S - current/max CPU (S)peed")
    print("  t - CPU (t)emperature")
    print("  f - (f)an speed")
    print("  m - (m)emory in use")
    print("  M - (M)emory in use/total")
    print("  c - used memory per(c)entage")
    print("  C - free memory per(C)entage")
    print("  w - s(w)ap memory in use")
    print("  W - s(W)ap memory in use/total")
    print("  x - swap usage in %")
    print("  d - (d)rives as names usage in %")
    print("  D - (D)rives as names used/total")
    print("  n - drives as mou(n)tpoints usage in %")
    print("  N - drives as mou(N)tpoints used/total")
    print("  u - (u)ptime HH:MM")
    print("  U - (U)ptime HH:MM:SS")
    print("  k - current networ(k) traffic as upload/download in kB/s")

    print("\n-F - use Fahrenheit instead of ℃")
    print("-N - display field names (except for (g)raphical CPU load bar)")
    print("-S<number> - number of spaces between components (-S2 if none given)")
    print("-S<string> for custom separator (use \' | \' to include spaces)")
    print("-M<string> for custom component name (\'My custom name: \')")
    print("-T - test execution time")
    print("-all - display all possible data (for use in terminal)\n")

    print("-I<component> - show an icon before text; 1 component per executor allowed")
    print("-W<number> - select 0 to n-th element from multiple output (drives, mountpoints)\n")


def icon_path(home, component):
    icons = {'g': '',
             'p': 'cpu.svg',
             'a': 'cpu.svg',
             'q': 'cpu.svg',
             'Q': 'cpu.svg',
             's': 'cpu.svg',
             'S': 'cpu.svg',
             't': 'temp.svg',
             'f': 'fan.svg',
             'm': 'mem.svg',
             'M': 'mem.svg',
             'c': 'mem.svg',
             'C': 'mem.svg',
             'w': 'swap.svg',
             'W': 'swap.svg',
             'x': 'swap.svg',
             'd': 'hdd.svg',
             'D': 'hdd.svg',
             'n': 'hdd.svg',
             'N': 'hdd.svg',
             'u': 'up.svg',
             'U': 'up.svg'}
    try:
        f_name = icons[component]
    except KeyError:
        return ""

    return icon_to_use(home, f_name)


def net_icon(home, ul, dl):

    if ul >= 0.01 and dl >= 0.01:
        f_name = "xfer-b.svg"
    elif ul >= 0.01:
        f_name = "xfer-u.svg"
    elif dl >= 0.01:
        f_name = "xfer-d.svg"
    else:
        f_name = "xfer.svg"

    return icon_to_use(home, f_name)


def icon_to_use(home, f_name):
    icon_custom = home + '/.local/share/psuinfo/' + f_name
    icon_default = "/usr/share/psuinfo/" + f_name
    if os.path.isfile(icon_custom):
        return icon_custom
    else:
        return icon_default


if __name__ == "__main__":
    main()
